package com.github.javpower.kvstore.model;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/github/javpower/kvstore/model/kv.proto

public final class Kv {
  private Kv() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KvPairOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KvPair)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>int64 expire_timestamp = 3;</code>
     * @return The expireTimestamp.
     */
    long getExpireTimestamp();
  }
  /**
   * Protobuf type {@code KvPair}
   */
  public static final class KvPair extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:KvPair)
      KvPairOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KvPair.newBuilder() to construct.
    private KvPair(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KvPair() {
      key_ = "";
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KvPair();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Kv.internal_static_KvPair_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Kv.internal_static_KvPair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Kv.KvPair.class, Kv.KvPair.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRE_TIMESTAMP_FIELD_NUMBER = 3;
    private long expireTimestamp_;
    /**
     * <code>int64 expire_timestamp = 3;</code>
     * @return The expireTimestamp.
     */
    @java.lang.Override
    public long getExpireTimestamp() {
      return expireTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      if (expireTimestamp_ != 0L) {
        output.writeInt64(3, expireTimestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      if (expireTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, expireTimestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Kv.KvPair)) {
        return super.equals(obj);
      }
      Kv.KvPair other = (Kv.KvPair) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (getExpireTimestamp()
          != other.getExpireTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + EXPIRE_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpireTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Kv.KvPair parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Kv.KvPair parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Kv.KvPair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Kv.KvPair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Kv.KvPair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Kv.KvPair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Kv.KvPair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Kv.KvPair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Kv.KvPair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Kv.KvPair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Kv.KvPair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Kv.KvPair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Kv.KvPair prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KvPair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KvPair)
        Kv.KvPairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Kv.internal_static_KvPair_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Kv.internal_static_KvPair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Kv.KvPair.class, Kv.KvPair.Builder.class);
      }

      // Construct using Kv.KvPair.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";

        value_ = "";

        expireTimestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Kv.internal_static_KvPair_descriptor;
      }

      @java.lang.Override
      public Kv.KvPair getDefaultInstanceForType() {
        return Kv.KvPair.getDefaultInstance();
      }

      @java.lang.Override
      public Kv.KvPair build() {
        Kv.KvPair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Kv.KvPair buildPartial() {
        Kv.KvPair result = new Kv.KvPair(this);
        result.key_ = key_;
        result.value_ = value_;
        result.expireTimestamp_ = expireTimestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Kv.KvPair) {
          return mergeFrom((Kv.KvPair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Kv.KvPair other) {
        if (other == Kv.KvPair.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (other.getExpireTimestamp() != 0L) {
          setExpireTimestamp(other.getExpireTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                value_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 24: {
                expireTimestamp_ = input.readInt64();

                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private long expireTimestamp_ ;
      /**
       * <code>int64 expire_timestamp = 3;</code>
       * @return The expireTimestamp.
       */
      @java.lang.Override
      public long getExpireTimestamp() {
        return expireTimestamp_;
      }
      /**
       * <code>int64 expire_timestamp = 3;</code>
       * @param value The expireTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setExpireTimestamp(long value) {
        
        expireTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 expire_timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpireTimestamp() {
        
        expireTimestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:KvPair)
    }

    // @@protoc_insertion_point(class_scope:KvPair)
    private static final Kv.KvPair DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Kv.KvPair();
    }

    public static Kv.KvPair getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KvPair>
        PARSER = new com.google.protobuf.AbstractParser<KvPair>() {
      @java.lang.Override
      public KvPair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KvPair> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KvPair> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Kv.KvPair getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StorageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Storage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .KvPair kv_pairs = 1;</code>
     */
    java.util.List<Kv.KvPair> 
        getKvPairsList();
    /**
     * <code>repeated .KvPair kv_pairs = 1;</code>
     */
    Kv.KvPair getKvPairs(int index);
    /**
     * <code>repeated .KvPair kv_pairs = 1;</code>
     */
    int getKvPairsCount();
    /**
     * <code>repeated .KvPair kv_pairs = 1;</code>
     */
    java.util.List<? extends Kv.KvPairOrBuilder> 
        getKvPairsOrBuilderList();
    /**
     * <code>repeated .KvPair kv_pairs = 1;</code>
     */
    Kv.KvPairOrBuilder getKvPairsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Storage}
   */
  public static final class Storage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Storage)
      StorageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Storage.newBuilder() to construct.
    private Storage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Storage() {
      kvPairs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Storage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Kv.internal_static_Storage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Kv.internal_static_Storage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Kv.Storage.class, Kv.Storage.Builder.class);
    }

    public static final int KV_PAIRS_FIELD_NUMBER = 1;
    private java.util.List<Kv.KvPair> kvPairs_;
    /**
     * <code>repeated .KvPair kv_pairs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<Kv.KvPair> getKvPairsList() {
      return kvPairs_;
    }
    /**
     * <code>repeated .KvPair kv_pairs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Kv.KvPairOrBuilder> 
        getKvPairsOrBuilderList() {
      return kvPairs_;
    }
    /**
     * <code>repeated .KvPair kv_pairs = 1;</code>
     */
    @java.lang.Override
    public int getKvPairsCount() {
      return kvPairs_.size();
    }
    /**
     * <code>repeated .KvPair kv_pairs = 1;</code>
     */
    @java.lang.Override
    public Kv.KvPair getKvPairs(int index) {
      return kvPairs_.get(index);
    }
    /**
     * <code>repeated .KvPair kv_pairs = 1;</code>
     */
    @java.lang.Override
    public Kv.KvPairOrBuilder getKvPairsOrBuilder(
        int index) {
      return kvPairs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < kvPairs_.size(); i++) {
        output.writeMessage(1, kvPairs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < kvPairs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, kvPairs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Kv.Storage)) {
        return super.equals(obj);
      }
      Kv.Storage other = (Kv.Storage) obj;

      if (!getKvPairsList()
          .equals(other.getKvPairsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getKvPairsCount() > 0) {
        hash = (37 * hash) + KV_PAIRS_FIELD_NUMBER;
        hash = (53 * hash) + getKvPairsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Kv.Storage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Kv.Storage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Kv.Storage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Kv.Storage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Kv.Storage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Kv.Storage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Kv.Storage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Kv.Storage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Kv.Storage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Kv.Storage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Kv.Storage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Kv.Storage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Kv.Storage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Storage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Storage)
        Kv.StorageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Kv.internal_static_Storage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Kv.internal_static_Storage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Kv.Storage.class, Kv.Storage.Builder.class);
      }

      // Construct using Kv.Storage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (kvPairsBuilder_ == null) {
          kvPairs_ = java.util.Collections.emptyList();
        } else {
          kvPairs_ = null;
          kvPairsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Kv.internal_static_Storage_descriptor;
      }

      @java.lang.Override
      public Kv.Storage getDefaultInstanceForType() {
        return Kv.Storage.getDefaultInstance();
      }

      @java.lang.Override
      public Kv.Storage build() {
        Kv.Storage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Kv.Storage buildPartial() {
        Kv.Storage result = new Kv.Storage(this);
        int from_bitField0_ = bitField0_;
        if (kvPairsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            kvPairs_ = java.util.Collections.unmodifiableList(kvPairs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.kvPairs_ = kvPairs_;
        } else {
          result.kvPairs_ = kvPairsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Kv.Storage) {
          return mergeFrom((Kv.Storage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Kv.Storage other) {
        if (other == Kv.Storage.getDefaultInstance()) return this;
        if (kvPairsBuilder_ == null) {
          if (!other.kvPairs_.isEmpty()) {
            if (kvPairs_.isEmpty()) {
              kvPairs_ = other.kvPairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureKvPairsIsMutable();
              kvPairs_.addAll(other.kvPairs_);
            }
            onChanged();
          }
        } else {
          if (!other.kvPairs_.isEmpty()) {
            if (kvPairsBuilder_.isEmpty()) {
              kvPairsBuilder_.dispose();
              kvPairsBuilder_ = null;
              kvPairs_ = other.kvPairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              kvPairsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getKvPairsFieldBuilder() : null;
            } else {
              kvPairsBuilder_.addAllMessages(other.kvPairs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                Kv.KvPair m =
                    input.readMessage(
                        Kv.KvPair.parser(),
                        extensionRegistry);
                if (kvPairsBuilder_ == null) {
                  ensureKvPairsIsMutable();
                  kvPairs_.add(m);
                } else {
                  kvPairsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<Kv.KvPair> kvPairs_ =
        java.util.Collections.emptyList();
      private void ensureKvPairsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          kvPairs_ = new java.util.ArrayList<Kv.KvPair>(kvPairs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Kv.KvPair, Kv.KvPair.Builder, Kv.KvPairOrBuilder> kvPairsBuilder_;

      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public java.util.List<Kv.KvPair> getKvPairsList() {
        if (kvPairsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(kvPairs_);
        } else {
          return kvPairsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public int getKvPairsCount() {
        if (kvPairsBuilder_ == null) {
          return kvPairs_.size();
        } else {
          return kvPairsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Kv.KvPair getKvPairs(int index) {
        if (kvPairsBuilder_ == null) {
          return kvPairs_.get(index);
        } else {
          return kvPairsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Builder setKvPairs(
          int index, Kv.KvPair value) {
        if (kvPairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvPairsIsMutable();
          kvPairs_.set(index, value);
          onChanged();
        } else {
          kvPairsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Builder setKvPairs(
          int index, Kv.KvPair.Builder builderForValue) {
        if (kvPairsBuilder_ == null) {
          ensureKvPairsIsMutable();
          kvPairs_.set(index, builderForValue.build());
          onChanged();
        } else {
          kvPairsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Builder addKvPairs(Kv.KvPair value) {
        if (kvPairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvPairsIsMutable();
          kvPairs_.add(value);
          onChanged();
        } else {
          kvPairsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Builder addKvPairs(
          int index, Kv.KvPair value) {
        if (kvPairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvPairsIsMutable();
          kvPairs_.add(index, value);
          onChanged();
        } else {
          kvPairsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Builder addKvPairs(
          Kv.KvPair.Builder builderForValue) {
        if (kvPairsBuilder_ == null) {
          ensureKvPairsIsMutable();
          kvPairs_.add(builderForValue.build());
          onChanged();
        } else {
          kvPairsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Builder addKvPairs(
          int index, Kv.KvPair.Builder builderForValue) {
        if (kvPairsBuilder_ == null) {
          ensureKvPairsIsMutable();
          kvPairs_.add(index, builderForValue.build());
          onChanged();
        } else {
          kvPairsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Builder addAllKvPairs(
          java.lang.Iterable<? extends Kv.KvPair> values) {
        if (kvPairsBuilder_ == null) {
          ensureKvPairsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, kvPairs_);
          onChanged();
        } else {
          kvPairsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Builder clearKvPairs() {
        if (kvPairsBuilder_ == null) {
          kvPairs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          kvPairsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Builder removeKvPairs(int index) {
        if (kvPairsBuilder_ == null) {
          ensureKvPairsIsMutable();
          kvPairs_.remove(index);
          onChanged();
        } else {
          kvPairsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Kv.KvPair.Builder getKvPairsBuilder(
          int index) {
        return getKvPairsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Kv.KvPairOrBuilder getKvPairsOrBuilder(
          int index) {
        if (kvPairsBuilder_ == null) {
          return kvPairs_.get(index);  } else {
          return kvPairsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public java.util.List<? extends Kv.KvPairOrBuilder> 
           getKvPairsOrBuilderList() {
        if (kvPairsBuilder_ != null) {
          return kvPairsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(kvPairs_);
        }
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Kv.KvPair.Builder addKvPairsBuilder() {
        return getKvPairsFieldBuilder().addBuilder(
            Kv.KvPair.getDefaultInstance());
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public Kv.KvPair.Builder addKvPairsBuilder(
          int index) {
        return getKvPairsFieldBuilder().addBuilder(
            index, Kv.KvPair.getDefaultInstance());
      }
      /**
       * <code>repeated .KvPair kv_pairs = 1;</code>
       */
      public java.util.List<Kv.KvPair.Builder> 
           getKvPairsBuilderList() {
        return getKvPairsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Kv.KvPair, Kv.KvPair.Builder, Kv.KvPairOrBuilder> 
          getKvPairsFieldBuilder() {
        if (kvPairsBuilder_ == null) {
          kvPairsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Kv.KvPair, Kv.KvPair.Builder, Kv.KvPairOrBuilder>(
                  kvPairs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          kvPairs_ = null;
        }
        return kvPairsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Storage)
    }

    // @@protoc_insertion_point(class_scope:Storage)
    private static final Kv.Storage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Kv.Storage();
    }

    public static Kv.Storage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Storage>
        PARSER = new com.google.protobuf.AbstractParser<Storage>() {
      @java.lang.Override
      public Storage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Storage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Storage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Kv.Storage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KvPair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KvPair_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=src/main/java/com/github/javpower/java" +
      "/kvstore/model/kv.proto\">\n\006KvPair\022\013\n\003key" +
      "\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\030\n\020expire_timestam" +
      "p\030\003 \001(\003\"$\n\007Storage\022\031\n\010kv_pairs\030\001 \003(\0132\007.K" +
      "vPairb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_KvPair_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KvPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KvPair_descriptor,
        new java.lang.String[] { "Key", "Value", "ExpireTimestamp", });
    internal_static_Storage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Storage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_descriptor,
        new java.lang.String[] { "KvPairs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
